
version: '3'
services:
  zipkin-container:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  service-discovery-container:
    build:
      context: ./service-discovery
    image: mouhib543/service-discovery
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  cloud-config-container:
    build:
      context: ./cloud-config
    image: mouhib543/cloud-config 
    ports:
      - 9296:9296
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  api-gateway-container:
    build:
      context: ./api-gateway
    image: mouhib543/api-gateway 
    ports:
      - 8085:8085
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  proxy-client-container:
    build:
      context: ./proxy-client
    image: mouhib543/proxy-client
    ports:
      - 8900:8900
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  order-service-container:
    build:
      context: ./order-service
    image: mouhib543/order-service
    ports:
      - 8300:8300
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  payment-service-container:
    build:
      context: ./payment-service
    image: mouhib543/payment-service
    ports:
      - 8400:8400
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  product-service-container:
    build:
      context: ./product-service
    image: mouhib543/product-service
    ports:
      - 8500:8500
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  shipping-service-container:
    build:
      context: ./shipping-service
    image: mouhib543/shipping-service
    ports:
      - 8600:8600
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  user-service-container:
    build:
      context: ./user-service
    image: mouhib543/user-service 
    ports:
      - 8700:8700
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  favourite-service-container:
    build:
      context: ./favourite-service
    image: mouhib543/favourite-service
    ports:
      - 8800:8800
    environment:
      - SPRING_PROFILES_ACTIVE=dev



