apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery-app
  labels:
    app: service-discovery-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery-app
  template:
    metadata:
      labels:
        app: service-discovery-app
    spec:
      containers:
        - name: service-discovery-app
          image: 
          imagePullPolicy: Always
          ports:
            - containerPort: 8761

---

apiVersion: v1
kind: Service
metadata:
  name: service-discovery-svc
spec:
  ports:
    - port: 80
      targetPort: 8761
  selector:
    app: service-discovery-app
