apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service-app
  labels:
    app: shipping-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service-app
  template:
    metadata:
      labels:
        app: shipping-service-app
    spec:
      containers:
        - name: shipping-service-app
          image: 
          imagePullPolicy: Always
          ports:
            - containerPort: 8600

---

apiVersion: v1
kind: Service
metadata:
  name: shipping-service-svc
spec:
  ports:
    - port: 80
      targetPort: 8600
  selector:
    app: shipping-service-app
